### ISSUE TITLE
Electron crash on Arch Linux with "GPU process isn't usable. Goodbye" - this fix works for me:

### ISSUE THREAD

**Issue by EgonSpengler** [trembon/switch-library-manager#41]
In vendor/astilectron/main.js, I added this line just above start();

`app.commandLine.appendSwitch('in-process-gpu');`

**Comment by trembon** [comment]
what i can see this is this file, https://github.com/asticode/astilectron/blob/master/main.js, correct? what i know i'm unable to modify this from this repo, but i'll see if i can add that flag in another way, or if you have a suggestion

**Comment by trembon** [comment]
closing due to no response

**Comment by lubosz** [comment]
I can reproduce this on the latest 1.9.0 release as well as when building the main branch.

@trembon Your suggested fix resolves the issue for me:
https://github.com/lubosz/switch-library-manager/commit/cccb82fe72c410c126e717ff61b780dfff727ada

Since the comically ancient version 11.4.3 of electron is used currently, upgrading that to current 36.7.1 will most likely also resolve the issue.

**Comment by trembon** [comment]
yeah, the thing is that electron is wrapped from go-astilectron which is no longer maintained, so whole thing would need replacing i think

**Comment by lubosz** [comment]
> yeah, the thing is that electron is wrapped from go-astilectron which is no longer maintained, so whole thing would need replacing i think

Noticed that when compiling. Is there another maintained project that could replace it?
Is it hard to replicate what it did in this projects build system?
